### ISSUE TITLE
PM2 causes backend to restart immediately after crashing due to a Fortnite Content DNS lookup "EAI_AGAIN" error

### ISSUE THREAD

**Issue by McMistrzYT** [McMistrzYT/Partypack#9]
possibly gotta fix the process.exit(-1)

**this issue makes the vps use a shitton of cpu and lags out the entire server**

**Comment by Beat-YT** [comment]
maybe just fallback to cache when lookup fails?

**Comment by McMistrzYT** [comment]
> maybe just fallback to cache when lookup fails?

that'd work - im gonna implement it in my next commit
